### PR TITLE
Added support for Django 2.1+ and Django 3.0/3.1

### PR DESCRIPTION
**Pull request by peterfarrell**
The method signature for `subclass_exception` now requires the `attached_to` positional argument starting in Django 2.1+.

### CODE REVIEW

**Comment by peterfarrell** [comment]
I updated the `tox.ini` file to support Django 2.1 and 2.2.

Django 2.0 was the last version to support Python 3.4.  I broke out the `envlist` for Django 2.1 and 2.2 on Python 3.5+ only.

**Comment by peterfarrell** [comment]
Nudge... would it be possible to get this merged and released to PyPi? (@gnrfan @joshmaker @ctbarna @dakrauth)

**Comment by fdintino** [comment]
Hi! Sorry for the long delay in getting back to you on this. Will be looking at merging this week.

**Comment by peterfarrell** [comment]
@fdintino Added in support for Django 3.0 and 3.1 into this PR. Any possibility of a merge and PyPI release?

**Comment by peterfarrell** [comment]
This PR is overcome by events and no longer relevant.

**Pull request closed without merging**
